### ISSUE TITLE
Levels wont show above heads

### ISSUE THREAD

**Issue by DanyardTheWolf** [Sk1er/Levelhead#1]

**Comment by TJRavenD** [comment]
Same problem if you solve this plz share with me

**Comment by boomboompower** [comment]
@DanyardTheWolf @TJRavenD 
should be fixed

**Comment by Asherlam** [comment]
Same Problem From Me. Pls Help Me

**Comment by Sk1er** [comment]
Make sure your ip is mc.hypixel.net. You might need to delete and re-add the server for it to work
