### ISSUE TITLE
Levels not showing.

### ISSUE THREAD

**Issue by Ducky12345** [Sk1er/Levelhead#2]
Hey,
I have tried everything, changing settings to try and see if i can fix it. But with no luck, i can't seem to get it working. The Gui comes up, but it is not showing any levels.

I have optifine, and messed around with some settings. Are there settings that need to be active to ensure the mod works?

I really need some help, thx.

**Comment by JyffOG** [comment]
Same for me!! It was working about a week ago and then it just stopped. Hope i can get some help.

**Comment by S6B** [comment]
Same for me!!

**Comment by Sk1er** [comment]
Make sure your ip is mc.hypixel.net. You might need to delete and re-add the server for it to work

**Comment by zisis912** [comment]
reopen the issue, it doesnt work again.

**Comment by asbyth** [comment]
reopen a 3 year old issue? gg
join our support discord at https://sk1er.club/support
